apiVersion: v1
kind: Pod
metadata: 
  name: resoruce-limit
spec:
  containers:
    - name: resource
      image: alpine
      command: ["sleep","3600"]
      resources: 
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits: 
          memory: "120Mi"
          cpu: "500m"