apiVersion: v1
kind: Pod
metadata: 
  name: startup-probe-http
spec: 
  containers: 
  - name: startup-probe
    image: k8s.scp.io/nginx
    startupprobe: 
      httpGet:
        path: /
        port: 80
      failureThreshold: 50
      periodSeconds: 10